-- Initial Mock Admin User
INSERT INTO users (username, password_hash, role, branch_name) 
VALUES ('admin', 'hashed_pw_here', 'master', 'Administración Global')
ON CONFLICT (username) DO NOTHING;

-- Insert mock branch users
INSERT INTO users (username, password_hash, role, branch_name) VALUES 
('sucursal_ccs', 'hashed_pw_here', 'branch', 'Sucursal Principal Caracas'),
('sucursal_mcbo', 'hashed_pw_here', 'branch', 'Sucursal Maracaibo'),
('sucursal_vln', 'hashed_pw_here', 'branch', 'Sucursal Valencia')
ON CONFLICT (username) DO NOTHING;

-- Insert mock reports for Caracas
INSERT INTO reports (branch, month, "workDays", "workHours", workers, preventive, curative, referrals, activities, comments) VALUES 
('Sucursal Principal Caracas', '2026-01', 22, 176, '{"monthly": 50, "daily": 5, "interns": 2, "total": 57}', '{"preEmployment": 5, "periodic": 10, "preVacation": 2, "postVacation": 2, "returnToWork": 1, "changeOfPost": 0, "total": 20}', '{"orl": 2, "cvs": 1, "gi": 3, "respiratory": 4, "eye": 1, "skin": 0, "dental": 0, "neuro": 1, "musculoskeletal": 5, "metabolic": 0, "trauma": 1, "occupational": 0, "common": 15, "suspectedOccupational": 0, "other": 2, "total": 35}', '{"ivss": 1, "privateLab": 4, "total": 5}', '{"workshops": 1, "hygieneInspections": 2, "riskAssessments": 1, "total": 4}', 'Buen mes de enero.'),
('Sucursal Principal Caracas', '2026-02', 20, 160, '{"monthly": 52, "daily": 4, "interns": 2, "total": 58}', '{"preEmployment": 3, "periodic": 15, "preVacation": 5, "postVacation": 1, "returnToWork": 0, "changeOfPost": 1, "total": 25}', '{"orl": 3, "cvs": 2, "gi": 1, "respiratory": 6, "eye": 2, "skin": 1, "dental": 0, "neuro": 0, "musculoskeletal": 8, "metabolic": 1, "trauma": 0, "occupational": 0, "common": 20, "suspectedOccupational": 0, "other": 1, "total": 45}', '{"ivss": 2, "privateLab": 5, "total": 7}', '{"workshops": 2, "hygieneInspections": 1, "riskAssessments": 1, "total": 4}', 'Aumento casos respiratorios.'),
('Sucursal Principal Caracas', '2026-03', 23, 184, '{"monthly": 50, "daily": 6, "interns": 3, "total": 59}', '{"preEmployment": 4, "periodic": 12, "preVacation": 3, "postVacation": 4, "returnToWork": 2, "changeOfPost": 0, "total": 25}', '{"orl": 1, "cvs": 1, "gi": 4, "respiratory": 2, "eye": 0, "skin": 2, "dental": 1, "neuro": 1, "musculoskeletal": 6, "metabolic": 0, "trauma": 2, "occupational": 1, "common": 14, "suspectedOccupational": 1, "other": 0, "total": 36}', '{"ivss": 1, "privateLab": 3, "total": 4}', '{"workshops": 1, "hygieneInspections": 3, "riskAssessments": 2, "total": 6}', 'Evaluación ergonómica realizada.')
ON CONFLICT (branch, month) DO NOTHING;

-- Insert mock reports for Maracaibo
INSERT INTO reports (branch, month, "workDays", "workHours", workers, preventive, curative, referrals, activities, comments) VALUES 
('Sucursal Maracaibo', '2026-01', 22, 176, '{"monthly": 30, "daily": 3, "interns": 1, "total": 34}', '{"preEmployment": 2, "periodic": 8, "preVacation": 1, "postVacation": 1, "returnToWork": 0, "changeOfPost": 0, "total": 12}', '{"orl": 1, "cvs": 1, "gi": 4, "respiratory": 2, "eye": 3, "skin": 2, "dental": 1, "neuro": 0, "musculoskeletal": 3, "metabolic": 1, "trauma": 1, "occupational": 0, "common": 10, "suspectedOccupational": 0, "other": 1, "total": 30}', '{"ivss": 0, "privateLab": 2, "total": 2}', '{"workshops": 0, "hygieneInspections": 1, "riskAssessments": 1, "total": 2}', 'Temperaturas altas en planta.'),
('Sucursal Maracaibo', '2026-02', 20, 160, '{"monthly": 31, "daily": 2, "interns": 1, "total": 34}', '{"preEmployment": 1, "periodic": 10, "preVacation": 2, "postVacation": 0, "returnToWork": 1, "changeOfPost": 0, "total": 14}', '{"orl": 2, "cvs": 2, "gi": 3, "respiratory": 3, "eye": 1, "skin": 4, "dental": 0, "neuro": 0, "musculoskeletal": 5, "metabolic": 2, "trauma": 2, "occupational": 0, "common": 12, "suspectedOccupational": 0, "other": 0, "total": 36}', '{"ivss": 1, "privateLab": 3, "total": 4}', '{"workshops": 1, "hygieneInspections": 1, "riskAssessments": 1, "total": 3}', ''),
('Sucursal Maracaibo', '2026-03', 23, 184, '{"monthly": 31, "daily": 4, "interns": 2, "total": 37}', '{"preEmployment": 4, "periodic": 5, "preVacation": 3, "postVacation": 3, "returnToWork": 0, "changeOfPost": 0, "total": 15}', '{"orl": 0, "cvs": 1, "gi": 2, "respiratory": 1, "eye": 1, "skin": 1, "dental": 2, "neuro": 1, "musculoskeletal": 4, "metabolic": 1, "trauma": 0, "occupational": 0, "common": 8, "suspectedOccupational": 0, "other": 1, "total": 23}', '{"ivss": 0, "privateLab": 1, "total": 1}', '{"workshops": 2, "hygieneInspections": 2, "riskAssessments": 1, "total": 5}', 'Jornada de salud visual de personal.')
ON CONFLICT (branch, month) DO NOTHING;

-- Insert mock reports for Valencia
INSERT INTO reports (branch, month, "workDays", "workHours", workers, preventive, curative, referrals, activities, comments) VALUES 
('Sucursal Valencia', '2026-01', 22, 176, '{"monthly": 40, "daily": 2, "interns": 0, "total": 42}', '{"preEmployment": 1, "periodic": 20, "preVacation": 0, "postVacation": 0, "returnToWork": 0, "changeOfPost": 0, "total": 21}', '{"orl": 0, "cvs": 0, "gi": 1, "respiratory": 1, "eye": 1, "skin": 0, "dental": 0, "neuro": 0, "musculoskeletal": 2, "metabolic": 0, "trauma": 4, "occupational": 1, "common": 5, "suspectedOccupational": 0, "other": 0, "total": 15}', '{"ivss": 1, "privateLab": 1, "total": 2}', '{"workshops": 1, "hygieneInspections": 1, "riskAssessments": 1, "total": 3}', 'Incidentes menores por caida.'),
('Sucursal Valencia', '2026-02', 20, 160, '{"monthly": 39, "daily": 2, "interns": 0, "total": 41}', '{"preEmployment": 0, "periodic": 15, "preVacation": 5, "postVacation": 0, "returnToWork": 1, "changeOfPost": 2, "total": 23}', '{"orl": 1, "cvs": 1, "gi": 2, "respiratory": 2, "eye": 0, "skin": 1, "dental": 3, "neuro": 0, "musculoskeletal": 4, "metabolic": 1, "trauma": 1, "occupational": 0, "common": 11, "suspectedOccupational": 1, "other": 0, "total": 28}', '{"ivss": 2, "privateLab": 2, "total": 4}', '{"workshops": 0, "hygieneInspections": 2, "riskAssessments": 2, "total": 4}', 'Semana preventiva industrial.'),
('Sucursal Valencia', '2026-03', 23, 184, '{"monthly": 42, "daily": 5, "interns": 2, "total": 49}', '{"preEmployment": 5, "periodic": 10, "preVacation": 2, "postVacation": 5, "returnToWork": 0, "changeOfPost": 0, "total": 22}', '{"orl": 2, "cvs": 0, "gi": 1, "respiratory": 4, "eye": 2, "skin": 2, "dental": 1, "neuro": 1, "musculoskeletal": 7, "metabolic": 0, "trauma": 2, "occupational": 0, "common": 16, "suspectedOccupational": 0, "other": 1, "total": 39}', '{"ivss": 1, "privateLab": 4, "total": 5}', '{"workshops": 3, "hygieneInspections": 1, "riskAssessments": 1, "total": 5}', 'Taller de levantamiento de cargas pesado.')
ON CONFLICT (branch, month) DO NOTHING;
